### ISSUE TITLE
Error: No se crea la máquina al darle al boton de "Lanzar Maquina Ahora "

### ISSUE THREAD

**Issue by YanTic** [Andres-Shadow/uqcloud#35]
El boton me redirige, crea el usuario temporal, pero no me crear ni lanza ninguna maquina virtual, en los ultimos cambios. Por favor revisar y corregir este error
@Andres-Shadow

**Comment by Andres-Shadow** [comment]
El problema se encontraba en la clase virtualMachineUtilities, especificamente en la función "CreateVirtualMachineFromSpecifications". Ya que al mandar las solicitudes a la cola de manejo de peticiones se debe hacer uso de una estructura json y no el mapa pues a la hora de procesar las solicitudes de la creación estos objetos no son interpretados. 

Para solucionarlo se debe codificar el mapa en un json y posteriormente decodificarlo para que garantizar que se interpreten los valores al crear máquinas virtuales.
