### ISSUE TITLE
Desactivar el botón de máquina rápida una vez fue accionado una primera vez

### ISSUE THREAD

**Issue by Andres-Shadow** [Andres-Shadow/uqcloud#40]
Actualmente, cuando se presiona el botón "Lanzar Máquina Ahora" en la interfaz del servidor web, se envían múltiples peticiones de creación al servidor de procesamiento mientras este aún está realizando el proceso de validación. Esto puede llevar a una sobrecarga innecesaria y a la creación de múltiples instancias no deseadas.

Para evitar este problema, se debería implementar la funcionalidad para inhabilitar el botón "Lanzar Máquina" mientras el proceso de validación está en curso. De esta manera, se evitará que el usuario envíe múltiples peticiones simultáneamente durante la validación inicial.

**Comment by YanTic** [comment]
Este pequeño cambio visual ha sido cambiado en [Merge pull request #41](https://github.com/Andres-Shadow/uqcloud/commit/3beb6d5be1ab4e4c89cda8e330dd3088f969b040)

Además de deshabilitar el boton, se ha agregado una alerta que le ayuda al usuario a saber porque el boton se ha deshabilitado mientras espera a que su vm instantanea se halla creado por completo.

**Comment by Andres-Shadow** [comment]
Good job!
